# Generated by Django 5.1.2 on 2025-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category_remove_menu_menu_item_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('reservation_date', 'reservation_slot'), name='unique_reservation_per_slot'),
        ),
    ]
