# Generated by Django 5.1.2 on 2025-01-29 15:40

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_unique_reservation_per_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.SmallIntegerField(default=10, validators=[restaurant.models.validate_positive]),
        ),
    ]
